// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjxqsddfhqjdkqbtzynl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqeHFzZGRmaHFqZGtxYnR6eW5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxODk5MDMsImV4cCI6MjA1NDc2NTkwM30.kkoDTUfay8vkyKTqke8uo1j7WX-AdvUX5ddDbBdH0Vg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);